import type { Code, IRCustomBlock, VueCodeInformation } from '@vue/language-core'
import { compileBlock } from '~/core/compile'
import type { CompileResult } from '~/core/compile'
import { PackageConfig } from '~/core/package-config'
import { declareClasses } from '~/core/declaration'
import type { BlockProblem } from '~/core/errors'
import { resolveOptions } from '~/core/options'
import type { TailwindBlockOptions } from '~/core/options'

const USER_SCRIPT_SOURCE_NAME = 'scriptSetup'
const TEMPLATE_CONTEXT_START = 'const __VLS_ctx = '
const TEMPLATE_CONTEXT_END = ';\n'
const CONTEXT_HELPER_NAME = '__tailwindBlockContext'
const CONTEXT_HELPER_DECLARATION = `declare function ${CONTEXT_HELPER_NAME}<Context, Variables>(context: Context, variables: Variables): Context & Variables;\n`

interface InjectionTarget {
  generatedCode: Code[]
  tailwindBlock: IRCustomBlock
  isTypeScript: boolean
  options: TailwindBlockOptions
}

/** Own copy, because older @vue/language-core versions do not export their codeFeatures. */
const VERIFICATION_FEATURES: VueCodeInformation = { verification: true }

/**
 * Mutates the generated TS of one component so the template and script can use the variable the
 * Vite plugin declares at runtime, and so yaml problems surface as errors on the block.
 */
export function injectTailwindBlock(target: InjectionTarget): void {
  const { generatedCode, tailwindBlock, isTypeScript } = target
  const { variableName } = resolveOptions(target.options)
  const compiled = compileBlock(tailwindBlock.content)
  const blockProblems = compiled.ok ? [] : compiled.problems

  insertBeforeUserScript(generatedCode, buildDeclaration(compiled, variableName, isTypeScript))

  const isExposedToTemplate = exposeVariableToTemplate(generatedCode, variableName)
  const reportedProblems = isExposedToTemplate
    ? blockProblems
    : [...blockProblems, buildUnsupportedCodegenProblem(tailwindBlock, variableName)]

  generatedCode.push(...buildProblemStatements(reportedProblems, tailwindBlock))
}

/** Surfaced on the block so a Vue upgrade that changes the generated code is noticed, not silent. */
function buildUnsupportedCodegenProblem(tailwindBlock: IRCustomBlock, variableName: string): BlockProblem {
  return {
    message:
      `${PackageConfig.name} could not expose "${variableName}" to the template: the code generated by ` +
      `this @vue/language-core version has an unexpected shape, so template usages are untyped.`,
    start: 0,
    end: tailwindBlock.content.length,
  }
}

/** Invalid yaml and plain js files get an untyped variable so they do not cascade into more errors. */
function buildDeclaration(compiled: CompileResult, variableName: string, isTypeScript: boolean): string {
  if (!compiled.ok || !isTypeScript) {
    return `const ${variableName}: any = undefined;\n`
  }

  return declareClasses(variableName, compiled.classTree, { asConst: true }) + '\n'
}

/** Declared first so top level script code can read it, and without a script setup it goes before the template context. */
function insertBeforeUserScript(generatedCode: Code[], declaration: string): void {
  const userScriptIndex = generatedCode.findIndex(isUserScriptSegment)
  const templateContextIndex = findContextStartIndex(generatedCode)
  const insertionIndex = userScriptIndex !== -1 ? userScriptIndex : templateContextIndex

  generatedCode.splice(Math.max(insertionIndex, 0), 0, declaration)
}

function isUserScriptSegment(code: Code): boolean {
  return typeof code !== 'string' && code[1] === USER_SCRIPT_SOURCE_NAME
}

/**
 * Returns whether it found Volar's context object to wrap.
 * Unknown template names compile to `__VLS_ctx.name`. Volar emits the context either as an object
 * literal or as one type expression, so wrap whatever it emitted in a helper that intersects it
 * with the variable. An intersection keeps every instance member, which a spread could drop.
 */
function exposeVariableToTemplate(generatedCode: Code[], variableName: string): boolean {
  const contextStartIndex = findContextStartIndex(generatedCode)
  const contextEndIndex = generatedCode.findIndex(
    (code, index) => index > contextStartIndex && code === TEMPLATE_CONTEXT_END,
  )

  if (contextStartIndex === -1 || contextEndIndex === -1) {
    return false
  }

  generatedCode.splice(contextEndIndex, 0, `, { ${variableName} })`)
  generatedCode[contextStartIndex] = `${TEMPLATE_CONTEXT_START}${CONTEXT_HELPER_NAME}(`
  generatedCode.splice(contextStartIndex, 0, CONTEXT_HELPER_DECLARATION)

  return true
}

function findContextStartIndex(generatedCode: Code[]): number {
  return generatedCode.findIndex((code) => typeof code === 'string' && code.includes(TEMPLATE_CONTEXT_START))
}

/**
 * A deliberately failing statement whose name maps onto the offending yaml, so the editor
 * underlines it. A mapped segment covers as many characters as its text, so the name is as long
 * as the range, and each statement gets its own block so equal names never clash.
 */
function buildProblemStatements(problems: BlockProblem[], tailwindBlock: IRCustomBlock): Code[] {
  return problems.flatMap((problem): Code[] => {
    const mappedName = '_'.repeat(Math.max(problem.end - problem.start, 1))

    return [
      '\n{ const ',
      [mappedName, tailwindBlock.name, problem.start, VERIFICATION_FEATURES],
      `: ${JSON.stringify(problem.message)} = 'invalid tailwind block' as string; }\n`,
    ]
  })
}
